#ifndef MAZE_H
#define MAZE_H

#include <vector>
#include <string>
#include <utility>

class Block;
class Player;

// Difficulty / generation mode chosen at the start screen.
//   EASY   : fixed tutorial maze loaded from maze_*.txt
//   NORMAL : generated by Recursive Backtracker (DFS)
//   HARD   : generated by Randomized Kruskal's
enum class GameMode { EASY, NORMAL, HARD };

// ----------------------------------------------------------------------------
// Maze : owns the 2D grid of Block* for one floor, plus all the bookkeeping
// for that floor (key count, the goal position, fog-of-war, etc.).
// ----------------------------------------------------------------------------
class Maze {
private:
    std::vector<std::vector<Block*>> grid;   // the map, stored as objects
    int nRow, nCol;
    int nKey;                                // keys required on this floor (= level)
    int level;
    bool useMovableGoal;                     // floors 3 & 4 use a MovableGoal
    int goalRow, goalCol;                    // current goal location
    bool levelCleared;
    bool darkMode;                           // extra module: pitch-black / no map memory
    bool fullBright;                         // extra module: whole map always visible
    bool replayTag;                          // showing a recorded replay
    bool spawnMonsters;                      // extra module: place monsters
    std::string message;                     // last status line shown in the HUD

    // Cells scheduled to turn into Empty after the current action resolves
    // (used so a Block never deletes itself mid-method).
    std::vector<std::pair<int, int>> toEmpty;

    void buildFromGrid(const std::vector<std::vector<int>>& nums);  // shared setup

    bool reachableAvoiding(const std::vector<std::pair<int, int>>& blocked,
                           const std::vector<std::pair<int, int>>& required) const;

public:
    Maze(int level, GameMode mode);
    ~Maze();

    int get_nRow() const { return nRow; }
    int get_nCol() const { return nCol; }
    int getNKey() const { return nKey; }
    int getLevel() const { return level; }
    void setDarkMode(bool v) { darkMode = v; }
    void setSpawnMonsters(bool v) { spawnMonsters = v; }
    void setFullBright(bool v) { fullBright = v; }
    void setReplayTag(bool v) { replayTag = v; }

    bool inBounds(int r, int c) const;
    Block* at(int r, int c);
    void setBlock(int r, int c, Block* b);   // delete old, install new

    void markEmpty(int r, int c) { toEmpty.push_back(std::make_pair(r, c)); }
    void commit();                           // apply scheduled removals

    void reveal(int r, int c);               // light up the 3x3 around (r,c)

    void printMaze(Player& player);          // clear screen + draw map + HUD

    bool isCleared() const { return levelCleared; }
    void setCleared(bool v) { levelCleared = v; }
    void setMessage(const std::string& m) { message = m; }

    void placeItems();                       // randomly drop keys/obstacles/portals
    bool usesMovableGoal() const { return useMovableGoal; }
    // Wander the MovableGoal one step. Avoids the player's cell so the goal
    // can never slide on top of the player (which would leave the player
    // standing on the goal without ever triggering the clear check).
    void moveGoalRandom(int playerRow, int playerCol);
    void setGoalPos(int r, int c) { goalRow = r; goalCol = c; }
};

#endif // MAZE_H
